### ISSUE TITLE
story(build): reset versions and add @sbb-esta npm namespace

### ISSUE THREAD

**Issue by kyubisation** [lyne-design-system/lyne-components#1067]
### Feature Description

We want to reset the version to 0.1.0 and use the @sbb-esta npm namespace.

### Definition of Done

- [x] Version is reset to 0.1.0
- [x] package.json name property is `@sbb-esta/lyne-components`
- [x] package.json contains `"publishConfig": { "access": "public" }` in order to allow namespaced publishes
- [ ] git tags are removed
- [x] CHANGELOG.md is renamed to CHANGELOG_LEGACY.md

**Comment by DavideMininni-Fincons** [comment]
Note: after merge to master all the references to 'lyne-test' MUST be changed.
See: https://github.com/search?q=org%3Alyne-design-system+%22lyne-test%22&type=code
