### ISSUE TITLE
story(sbb-button): review/refactor

### ISSUE THREAD

**Issue by kyubisation** [lyne-design-system/lyne-components#1131]
### Feature Description

We want to review/refactor the `lyne-button` implementation.

https://lyne.sbb.ch/components/lyne-button

[Figma Spec](https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=140%3A8)

**Design Spec**
- See Figma spec

**Technical Spec**
- Slot instead of label
- Should internally either use `<button>` or `<a>` (or `<span>` with visual only)
  - Should default to `<button>`
  - Should support all attributes from both `<button>` or `<a>` but only use the appropriate ones
- Inline button mixins if possible
- Error should not short circuit
- Internally check if icon is used and use named slot for icons
- Remove sbb-link-button
- Refactor negative variant according to guidelines (add property negative: boolean separate from variant property)

```html
<sbb-button>Action</sbb-button>
```

### Definition of Done

- [ ] Component is implemented
- [ ] Documentation is added
- [ ] Tests are implemented
- [ ] E2E Tests are implemented
- [ ] Storybook stories are implemented
- [ ] Navigation via keyboard is tested
- [ ] Screen reader output is tested
- [ ] High-contrast is tested
- [ ] Remaining accessibility is tested
- [ ] UX approved

**Comment by sebastiencloss** [comment]
Will be made Team-Lynx

**Comment by kyubisation** [comment]
Please have a close look at the sbb-link PR #1292
