### ISSUE TITLE
lyne-custom-toggle

### ISSUE THREAD

**Issue by OkanBostan** [lyne-design-system/lyne-components#1133]
- state: open
- internal refs: 12429
- figma: https://www.figma.com/file/oA9B5W6w0449gtItDzLS86/00%3A-Components?node-id=547%3A547982

### Feature Description
We want to review/refactor the lyne-button implementation.

https://lyne.sbb.ch/components/lyne-button

[Figma Spec] (https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=140%3A8)

**Design Spec**
-

**Technical Spec**

- 

### Definition of Done

 - [ ] Component is implemented
 - [ ]  Tests are implemented
 - [ ]  E2E Tests are implemented
 - [ ]  Storybook stories are implemented
 - [ ]  Navigation via keyboard is tested
 - [ ]  Screen reader output is tested
 - [ ]  High-contrast is tested
 - [ ]  Remaining accessibility is tested
 - [ ]  UX approved

**Comment by mcilurzo** [comment]
this ticket is obsolete. the requirements are covered by https://github.com/lyne-design-system/lyne-components/issues/1169
