### ISSUE TITLE
story(sbb-loading-indicator): initial implementation

### ISSUE THREAD

**Issue by OkanBostan** [lyne-design-system/lyne-components#1165]
### Feature Description
The `sbb-loading-indicator` component is used as a progress bar to indicate progress and activity.
[Figma Spec](https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=169%3A27458)

**References**
- https://angular.app.sbb.ch/angular/components/loading-indicator/overview
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role

**Design Spec**
- Supports two types of animation: `window` (default) which is supposed to cover the parent element (for large areas, see `fullbox` mode in SBB Angular library), and `circle` to be inlined within a text and adjusts the size to the font size (e.g. in buttons) 
- Has two sizes: `small` (default), `large`

**Technical Spec**
- `@Prop() variant?: 'window' | 'circle'` to indicate the type of the animation (default to 'window')
- `@Prop() size?: 's' | 'l'` to indicate the size of the `window` variant (default to 's')
- Investigate the best approach for accessibility, for example with aria-live="polite" (see SBB Angular library)
- Circle animation needs to be done from scratch

**Accessibility**
- Mürsel feedback: _"Since these elements are only temporarily displayed on the page, it is difficult for users to access and perceive them with a screen reader. Instead, it would be better for developers to announce a status message via aria-live for screen reader users."_

```html
<div>
  <p>Container's content.</p>
  <sbb-loading-indicator variant="window" size="s" aria-label="Loading, please wait" />
</div>

<sbb-button disabled>
  <sbb-loading-indicator slot="icon" variant="circle" />
  Loading
</sbb-button>
```

### Definition of Done

 - [ ] Component is implemented
 - [ ]  Tests are implemented
 - [ ]  E2E Tests are implemented
 - [ ]  Storybook stories are implemented
 - [ ]  Navigation via keyboard is tested
 - [ ]  Screen reader output is tested
 - [ ]  High-contrast is tested
 - [ ]  Remaining accessibility is tested
 - [ ]  UX approved

**Comment by mcilurzo** [comment]
Small as default is OK for me. I have adjusted the following in figma: 
Small = Default
Large = Large

**Comment by jeripeierSBB** [comment]
> Small as default is OK for me. I have adjusted the following in figma: Small = Default Large = Large

So far we use T shirt sizes for all "size" properties. should this not also be continued here?

**Comment by mcilurzo** [comment]
Yes, you are right. Then there are the following sizes:
S (default)
L
OK?

**Comment by jeripeierSBB** [comment]
@mcilurzo For me, yes :)
