### ISSUE TITLE
story(sbb-divider): initial implementation

### ISSUE THREAD

**Issue by OkanBostan** [lyne-design-system/lyne-components#1167]
### Feature Description

We want to provide the sbb-divider component.

[Figma Spec](https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=1456%3A681232)

**References**

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr
- https://material.angular.io/components/divider/overview

**Design Spec**

- Should be display block
- Visual representation of divider should be done with border styling

**Technical Spec**

- Provide property `orientation` with possible values `'horizontal' | 'vertical'`. Defaults to `horizontal`.
- Should add `role="separator"` and `aria-orientation={orientation}`

### Definition of Done

 - [ ]  Component is implemented
 - [ ]  Documentation is provided
 - [ ]  Tests are implemented
 - [ ]  E2E Tests are implemented
 - [ ]  Storybook stories are implemented
 - [ ]  Navigation via keyboard is tested
 - [ ]  Screen reader output is tested
 - [ ]  High-contrast is tested
 - [ ]  Remaining accessibility is tested
 - [ ]  UX approved

**Comment by sebastiencloss** [comment]
will be done by team-lynx
