### ISSUE TITLE
story(sbb-breadcrumb): initial implementation

### ISSUE THREAD

**Issue by OkanBostan** [lyne-design-system/lyne-components#1168]
### Feature Description

We want to implement breadcrumbs.

[Figma Spec](https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=140%3A7&t=7TzrbAR1Up3rPLYc-1)

**References**

- https://www.w3.org/WAI/ARIA/apg/patterns/breadcrumb/

**Design Spec**

- Implement an animation and discuss with @mcilurzo
- Open decision; Should the breadcrumbs be scrollable when exceeding width or wrap around. @mcilurzo 

**Technical Spec**

sbb-breadcrumb:
- unnamed slot for text
- needs props for the link: `href`, `rel`, `target`, `download` (compare with other link implementations)
- provide icon-name property and icon slot, which if both an icon and text (or any content in the unnamed slot) is slotted, use the common 2x spacing between icon and content
- when the content of the breadcrumb is too long, it should be hidden via ellipsis

Example
`<sbb-breadcrumb href="/products">Products</sbb-breadcrumb>`

sbb-breadcrumb-group:
- should have role `navigation`
- unnamed slot for sbb-breadcrumb instances
- first breadcrumb is by design always the home icon, but we do not restrict this in any way (See example)
- handles separators between breadcrumbs. This follows the same pattern as link list, in internally using an ol/li pattern
- the last sbb-breadcrumb instance should have `aria-current` applied
- The breadcrumbs should be navigatable via tab key as normal and it should support navigating with arrow keys (with wrap around)
- When the breadcrumb group exceeds maximum available width, it should collapse and display only the first and the last breadcrumb and a button `...` (`&hellip;`) as an inbetween element, which, when clicked, expands all breadcrumbs (and removes the button)
  - The button is most likely just a native button and it should have an aria-label describing its purpose (translated)

Example
```html
<sbb-breadcrumb-group>
  <sbb-breadcrumb href="/" icon-name="house-medium"></sbb-breadcrumb>
  <sbb-breadcrumb href="/products">Products</sbb-breadcrumb>
</sbb-breadcrumb-group>
```

### Definition of Done

 - [ ] Component is implemented
 - [ ]  Tests are implemented
 - [ ]  E2E Tests are implemented
 - [ ]  Storybook stories are implemented
 - [ ]  Navigation via keyboard is tested
 - [ ]  Screen reader output is tested
 - [ ]  High-contrast is tested
 - [ ]  Remaining accessibility is tested
 - [ ]  UX approved

**Comment by DavideMininni-Fincons** [comment]
Notes for tech spec:

sbb-breadcrumb
- slot or `label` prop for text
- `active` prop 
- `disabled` prop 
- use sbb-link or use plain text? if plain text, it will need props for the link: `href`, `rel`, `target`, `download`

Example
`<sbb-breadcrumb href="/products">Products</sbb-breadcrumb>`

`<sbb-breadcrumb href="https://www.google.com" label="Search" target="_blank"></sbb-breadcrumb>`

`<sbb-breadcrumb href="/products"><sbb-link size="s" variant="inline">Products</sbb-link></sbb-breadcrumb>`


sbb-breadcrumbs
- slot for breadcrumb
- first breadcrumb is always the home icon -> sbb-icon or sbb-button in icon-only mode?
- handles separators between breadcrumbs
- `maxItems` prop: show home icon + dots + last breadcrumb if the number of breadcrumbs exceeds the value of `maxItems`=> are dots clickable to expand all breadcrumbs / present them in a popover? (see ionic behavior)

Example
`<sbb-breadcrumbs><sbb-breadcrumb href="/products">Products</sbb-breadcrumb></sbb-breadcrumbs>`
