### ISSUE TITLE
lyne-header

### ISSUE THREAD

**Issue by OkanBostan** [lyne-design-system/lyne-components#1172]
- state: open
- internal refs: 12420, 12416, 12417, 12418, 12419, 12421, 
- figma: https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=1220%3A686725

### Feature Description
We want to review/refactor the lyne-button implementation.

https://lyne.sbb.ch/components/lyne-button

[Figma Spec](https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=1220%3A686725)

**References**
- 12420
- 12416
- 12417
- 12418
- 12419
- 12421

**Design Spec**
-

**Technical Spec**

- 

### Definition of Done

 - [ ] Component is implemented
 - [ ]  Tests are implemented
 - [ ]  E2E Tests are implemented
 - [ ]  Storybook stories are implemented
 - [ ]  Navigation via keyboard is tested
 - [ ]  Screen reader output is tested
 - [ ]  High-contrast is tested
 - [ ]  Remaining accessibility is tested
 - [ ]  UX approved

**Comment by Acika00mk** [comment]
It will be done by Lynx team

**Comment by kyubisation** [comment]
Succeeded by #1312
