### ISSUE TITLE
lyne-timetable-row-day-change

### ISSUE THREAD

**Issue by OkanBostan** [lyne-design-system/lyne-components#1181]
- state: in progress
- figma: 
- dev: https://lyne.sbb.ch/components/lyne-timetable-row-day-change
- ux quality-check
- code quality-check
- refactoring (optionaly)
- testing

### Feature Description
We want to review/refactor the lyne-button implementation.

https://lyne.sbb.ch/components/lyne-button

[Figma Spec]

- dev: https://lyne.sbb.ch/components/lyne-timetable-row-day-change

**References**
-  

**Design Spec**
-

**Technical Spec**

- 

### Definition of Done

 - [ ]  ux quality-check
 - [ ]  code quality-check
 - [ ]  refactoring (optionaly)
 - [ ]  testing
 - [ ]  Component is implemented
 - [ ]  Tests are implemented
 - [ ]  E2E Tests are implemented
 - [ ]  Storybook stories are implemented
 - [ ]  Navigation via keyboard is tested
 - [ ]  Screen reader output is tested
 - [ ]  High-contrast is tested
 - [ ]  Remaining accessibility is tested
 - [ ]  UX approved

**Comment by jeripeierSBB** [comment]
Will be tracked/decided in #1901
