### ISSUE TITLE
story(global-styles): remove default scss mode and make shared default

### ISSUE THREAD

**Issue by jeripeierSBB** [lyne-design-system/lyne-components#1185]
### Feature Description

We want to remove the default scss files and make the shared scss file the default/only variant.
Additionally we want to provide and use a global (s)css file for consumers and our storybook.

### Definition of Done

- [ ] Component is implemented
- [ ] Tests are implemented/adapted
- [ ] E2E Tests are implemented/adapted
- [ ] Storybook stories are implemented/adapted

**Comment by kyubisation** [comment]
Closed by #1281
