### ISSUE TITLE
lyne-stack

### ISSUE THREAD

**Issue by OkanBostan** [lyne-design-system/lyne-components#1225]
- state: in progress

### Feature Description
We want to review/refactor the lyne-button implementation. 
 
[Figma Spec]  (???)
- dev: https://lyne.sbb.ch/components/lyne-stack

**References**
-  
- 
- 

**Design Spec**
- Discuss with @mcilurzo

**Technical Spec**

- 

### Definition of Done
 - [ ]  ux quality-check
 - [ ]  Code quality-check
 - [ ]  Refactoring (optional)
 - [ ]  Testing
 - [ ]  Component is implemented
 - [ ]  Tests are implemented
 - [ ]  E2E Tests are implemented
 - [ ]  Storybook stories are implemented
 - [ ]  Navigation via keyboard is tested
 - [ ]  Screen reader output is tested
 - [ ]  High-contrast is tested
 - [ ]  Remaining accessibility is tested
 - [ ]  UX approved

**Comment by liviakuenzli** [comment]
We would like to have the option to add a background-color and a background-image to the stack.

**Comment by kyubisation** [comment]
@liviakuenzli We discussed this internally. We are likely to remove this component and will provide SCSS mixins for this use case. This also allows greater flexibility for you (e.g. background-color and background-image).
