### ISSUE TITLE
lyne-section

### ISSUE THREAD

**Issue by OkanBostan** [lyne-design-system/lyne-components#1230]
- state: in progress
- figma: ???
- dev: https://lyne.sbb.ch/components/lyne-section
- ui-glitch in safari.
- ux quality-check
- code quality-check
- refactoring (optionaly)
- testing
- Discuss purpose with @mcilurzo

### Feature Description
We want to review/refactor the lyne-button implementation.
- Discuss purpose with @mcilurzo

[Figma Spec](???)
- dev: https://lyne.sbb.ch/components/lyne-section

**References**
-  
-  
-  

**Design Spec**
-

**Technical Spec**

- 

### Definition of Done
 - [ ]  ui-glitch in safari
 - [ ]  ux quality-check
 - [ ]  code quality-check
 - [ ]  refactoring (optionaly)
 - [ ]  testing
 - [ ] Component is implemented
 - [ ]  Tests are implemented
 - [ ]  E2E Tests are implemented
 - [ ]  Storybook stories are implemented
 - [ ]  Navigation via keyboard is tested
 - [ ]  Screen reader output is tested
 - [ ]  High-contrast is tested
 - [ ]  Remaining accessibility is tested
 - [ ]  UX approved

**Comment by liviakuenzli** [comment]
We would like to have the option to add a background-color and a background-image to the section.

**Comment by kyubisation** [comment]
@liviakuenzli We discussed this internally. We are likely to remove this component and will provide SCSS mixins for this use case. This also allows greater flexibility for you (e.g. background-color and background-image).
