### ISSUE TITLE
lyne-card-product

### ISSUE THREAD

**Issue by OkanBostan** [lyne-design-system/lyne-components#1232]
### Feature Description
We want to review/refactor the lyne-button implementation.

https://lyne.sbb.ch/components/lyne-button

[Figma Spec] (???)

- dev: https://lyne.sbb.ch/components/lyne-card-product

**References**

-

**Design Spec**
-  Discuss hover offset with @mcilurzo
-  isButton/hrefValue vs href
-  Always render slots
-  Discuss inclusion or exclusion of button or a element inside the render (or outside the element)
-  appearance vs :host-context
-  Replace accessibilityLabel with aria-label, aria-labelledby and aria-describedby forwardings
-  Replace isDisabled with disabled

**Technical Spec**

- 

### Definition of Done

 - [ ]  Component is implemented
 - [ ]  Tests are implemented
 - [ ]  E2E Tests are implemented
 - [ ]  Storybook stories are implemented
 - [ ]  Navigation via keyboard is tested
 - [ ]  Screen reader output is tested
 - [ ]  High-contrast is tested
 - [ ]  UX approved
 - [ ]  Remaining accessibility is tested

**Comment by jeripeierSBB** [comment]
deleted, should not be part of the design system.
