### ISSUE TITLE
lyne-text-input

### ISSUE THREAD

**Issue by OkanBostan** [lyne-design-system/lyne-components#1235]
- state: in progress
- internal refs: 12428
- figma: https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=140%3A23
- dev: https://lyne.sbb.ch/components/lyne-text-input
- ux quality-check
- code quality-check
- refactoring (optionaly)
- testing
- Refactor to form field?

### Feature Description
We want to review/refactor the lyne-text-input implementation.

[Figma Spec] (https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=140%3A23)

- dev: https://lyne.sbb.ch/components/lyne-text-input

**References**
- 12428
-

**Design Spec**
-

**Technical Spec**

- 

### Definition of Done
 - [ ]  ux quality-check
 - [ ]  code quality-check
 - [ ]  refactoring (optionaly)
 - [ ]  testing
 - [ ]  Component is implemented
 - [ ]  Tests are implemented
 - [ ]  E2E Tests are implemented
 - [ ]  Storybook stories are implemented
 - [ ]  Navigation via keyboard is tested
 - [ ]  Screen reader output is tested
 - [ ]  High-contrast is tested
 - [ ]  Remaining accessibility is tested
 - [ ]  UX approved

**Comment by sebastiencloss** [comment]
+ add the possibility to set the focus in it (programmatically, from outside) by event. 
Usage from outside:

`const myFocusEvent = new CustomEvent("customSetFocus", { detail: {}});

const inputComponent = document.querySelector("sbb-text-input");
inputComponent.dispatchEvent(myFocusEvent);`

**Comment by kyubisation** [comment]
`lyne-text-input` will be replaced by `sbb-form-field` and with its new structure, you should be able to place focus directly on the input element.
