### ISSUE TITLE
story(sbb-link): review/refactor

### ISSUE THREAD

**Issue by OkanBostan** [lyne-design-system/lyne-components#1239]
### Feature Description
We want to review/refactor the lyne-button implementation.

[Figma Spec] (https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=615%3A530767)

- dev: https://lyne.sbb.ch/components/lyne-link

**References**

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Design Spec**
- See Figma spec

**Technical Spec**
- Slot instead of label
- Should internally either use `<button>` or `<a>` (or `<span>` with visual only)
  - Should render an `<a>` element when `href` is used, when `href` is not provided use `<button>` element
  - Should support all attributes from both `<button>` or `<a>` but only use the appropriate ones
  - Should add property `static` to indicate, that internally the `<span>` should be used (To discuss: Discussion about ancester detection)
- Error should not short circuit
- Internally check if icon is used and use named slot for icons
- Refactor negative variant according to guidelines (add property negative: boolean separate from variant property)

```html
<sbb-link href="...">Action</sbb-link>
```

### Definition of Done
 - [x]  Component is implemented
 - [x]  Tests are implemented
 - [x]  E2E Tests are implemented
 - [x]  Storybook stories are implemented
 - [x]  Navigation via keyboard is tested
 - [x]  Screen reader output is tested
 - [ ]  High-contrast is tested
 - [x]  Remaining accessibility is tested
 - [x]  UX approved

**Comment by sebastiencloss** [comment]
Will be made Team-Lynx
