### ISSUE TITLE
refactoring: sbb-card-badge

### ISSUE THREAD

**Issue by OkanBostan** [lyne-design-system/lyne-components#1242]
### Feature Description
We want to review/refactor the sbb-card-badge implementation.

[Figma Spec] (https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=1341%3A636046)

- Skew separate element on the left instead of whole element (avoids text unskew)
- Discuss removal of isDiscount, text and price with @mcilurzo (should be left to user)
- Discuss spacings between texts with @mcilurzo
- Is title attribute intended? @mcilurzo
- Replace accessibilityLabel with aria-label, aria-labelledby and aria-describedby forwardings
- Remove size
- Replace appearance with :host-context selectors
- Always render slots (remove check in componentWillLoad)

**Technical Spec**

- 

### Definition of Done

 - [ ] Component is implemented
 - [ ]  Tests are implemented
 - [ ]  E2E Tests are implemented
 - [ ]  Storybook stories are implemented
 - [ ]  Navigation via keyboard is tested
 - [ ]  Screen reader output is tested
 - [ ]  High-contrast is tested
 - [ ]  Remaining accessibility is tested
 - [ ]  UX approved

**Comment by jeripeierSBB** [comment]
done as part of #1833
