### ISSUE TITLE
story(sbb-clock): review/refactor

### ISSUE THREAD

**Issue by OkanBostan** [lyne-design-system/lyne-components#1243]
### Feature Description
We want to review/refactor the sbb-clock implementation.

https://lyne.sbb.ch/components/sbb-clock

[Figma Spec](https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=836%3A663362)

**References**

-

**Design Spec**

- Initial time is reset on tab switch/visibility switch/pause. Purpose @mcilurzo?

**Technical Spec**

- Check implementation and refactor where necessary
- Remove `paused` and `initialTime` properties and refactor related logic
  - Add possibility to add `data-now="1674125992598"` where the number is a timestamp, which sets a fixed time for the clock (it does not update)
- Ensure the sizing and position is always correct (there is a hard to reproduce bug that moves the hands into weird positions)
- Verify orientation change bug (changing orientation in the sbb-footer story on a smartphone from portrait to landscape and back)

```ts
// Example for current time
private _now(): number {
  if (this._element.dataset?.now) {
    const dataNow = +this._element.dataset?.now;
    return isNaN(dataNow) ? Date.now() : dataNow;
  }
  return Date.now();
}
```

### Definition of Done
 - [ ]  Component is implemented
 - [ ]  Documentation is provided
 - [ ]  Tests are implemented
 - [ ]  E2E Tests are implemented
 - [ ]  Storybook stories are implemented
 - [ ]  Navigation via keyboard is tested
 - [ ]  Screen reader output is tested
 - [ ]  High-contrast is tested
 - [ ]  Remaining accessibility is tested
 - [ ]  UX approved

**Comment by jeripeierSBB** [comment]
Issue on iOS: when changing device orientation, the clock sometimes is not displayed correctly anymore.
