### ISSUE TITLE
story(sbb-image): review/refactor

### ISSUE THREAD

**Issue by OkanBostan** [lyne-design-system/lyne-components#1245]
### Feature Description

We want to review/refactor the lyne-image implementation.

**References**

- Current implementation: https://lyne.sbb.ch/components/sbb-image

**Design Spec**

- https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=140%3A34

**Technical Spec**

- Refactor URL and query params handling to use native URL and URLSearchParams
- Remove hideFromScreenreader as this can be controlled by consumers directly via aria attributes
- Remove the variant property, if there is only one variant of this component
- Review/refactor implementation

### Definition of Done
 - [x]  Component is implemented
 - [x]  Documentation is added
 - [x]  Tests are implemented
 - [x]  E2E Tests are implemented
 - [x]  Storybook stories are implemented
 - [ ]  Navigation via keyboard is tested
 - [ ]  Screen reader output is tested
 - [ ]  High-contrast is tested
 - [ ]  Remaining accessibility is tested
 - [ ]  UX approved

**Comment by osminaz** [comment]
Hey, we want to use this component in the lyne-teaser-thumbnail component. But the margin and the aspect ratio styles are not flexibel. Can you also pay attention to this use case?

Link to the component: https://www.figma.com/file/oA9B5W6w0449gtItDzLS86/00%3A-Components?node-id=158%3A186992

**Comment by sebastiencloss** [comment]
> Hey, we want to use this component in the lyne-teaser-thumbnail component. But the margin and the aspect ratio styles are not flexibel. Can you also pay attention to this use case?
> 
> Link to the component: https://www.figma.com/file/oA9B5W6w0449gtItDzLS86/00%3A-Components?node-id=158%3A186992

same for the SearchResults-Page.. (team Lynx)
