### ISSUE TITLE
story(sbb-timetable-row): layout and animation

### ISSUE THREAD

**Issue by osminaz** [lyne-design-system/lyne-components#1298]
### Feature Description

We want to provide a dynamic layout and animation for the [sbb-timetable-row](https://github.com/lyne-design-system/lyne-components/issues/1291) component. 

**Figma Specs**
[Timetable results Specs](https://www.figma.com/file/0pGd1tS4HLCDUf5U1qQpxn/03%3A-Design-%E2%80%93-Home-2.0-Timetable-results?node-id=2%3A14842)

[Timetable-row Specs](https://www.figma.com/file/oA9B5W6w0449gtItDzLS86/00%3A-Components?node-id=388%3A485158)

[Timetable-row Skeleton](https://www.figma.com/file/0pGd1tS4HLCDUf5U1qQpxn/03%3A-Design-%E2%80%93-Home-2.0-Timetable-results?node-id=4376%3A529921)

**References**
   - Current implementation: https://lyne.sbb.ch/components/sbb-timetable-row

**Design Spec**
   - bottom of the component can have up to 2 lines -> (space-between)
   - loading state -> animation

**Technical Spec**
- provide a state for loading

### Definition of Done

- [ ] Component is implemented
- [ ] Tests are implemented
- [ ] E2E Tests are implemented
- [ ] Storybook stories are implemented
- [ ] Navigation via keyboard is tested
- [ ] Screen reader output is tested
- [ ] High-contrast is tested
- [ ] Remaining accessibility is tested
- [ ] UX approved

**Comment by jeripeierSBB** [comment]
Will be tracked/decided in #1901
