### ISSUE TITLE
story(sbb-timetable-row): markup and structure

### ISSUE THREAD

**Issue by osminaz** [lyne-design-system/lyne-components#1299]
### Feature Description

We want provide a new markup for the `sbb-timetable-row` component. 

**Figma Specs**
[Timetable results Specs](https://www.figma.com/file/0pGd1tS4HLCDUf5U1qQpxn/03%3A-Design-%E2%80%93-Home-2.0-Timetable-results?node-id=2%3A14842)

[Timetable-row Specs](https://www.figma.com/file/oA9B5W6w0449gtItDzLS86/00%3A-Components?node-id=388%3A485158)

[Timetable-row Skeleton](https://www.figma.com/file/0pGd1tS4HLCDUf5U1qQpxn/03%3A-Design-%E2%80%93-Home-2.0-Timetable-results?node-id=4376%3A529921)

[Card Specs](https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=1347%3A636897)

**References**
   - Current implementation: https://lyne.sbb.ch/components/sbb-timetable-row

**Technical Spec**
- provide aria attribute for the button: aria-label, aria-haspopup, aria-expanded and aria-controls
- set the role to "presentation" for the components button-wrapper and the role="row", role="rowHeader" and  role="gridcell" for the inner Elements

- We want to use these two components as slots:
   - sbb-card-badge,
   - sbb-pearl-chain
- We want to provide flat Props, which will be orientated to the visual specs:
    - Up:
        - pictogram: string
        - transportNumber: string // could be an icon or a rendered string?
        - direction: string <-- truncate logic
    - Middle: 
        - walkTimeBefore?: string, // footPath
        - walkTimeAfter?: string, // footPath
        - leftTime: string, // departureTime - tbd: delay?
        - rightTime: string, // arrivalTime - tbd: delay?
    - bottom:
        - plattform: string tbd: variants?
        - occupancyFirstClass?: "unknown" | "low" | "medium" | "high"
        - occupancySecondClass?: "unknown" | "low" | "medium" | "high"
        - travelHints?: Array
        - duration: string,
        - warning: string

Markup: 
```html
<sbb-timetable-row-button>
  <sbb-card>
      <slot name="cardBadge">
      ...
      ...
      <slot name="pearlChain">
      ...
      ...
   </sbb-card>
</sbb-timetable-row-button>
```

### Definition of Done

- [ ] Component is implemented
- [ ] Tests are implemented
- [ ] E2E Tests are implemented
- [ ] Storybook stories are implemented
- [ ] Navigation via keyboard is tested
- [ ] Screen reader output is tested
- [ ] High-contrast is tested
- [ ] Remaining accessibility is tested
- [ ] UX approved

**Comment by jeripeierSBB** [comment]
Will be tracked/decided in #1901
