### ISSUE TITLE
Bug: Custom events are not handled properly in React

### ISSUE THREAD

**Issue by osminaz** [lyne-design-system/lyne-components#1333]
Issue:
Custom events are not handled properly, as well as properties/attributes that are not a string or number. 

Solution:
By using Stencil's component wrappers, you can solve these issues and receive first-class React components.

Reference: https://stenciljs.com/docs/react

Package: https://github.com/ionic-team/stencil-ds-output-targets/blob/main/packages/react-output-target/README.md

**Comment by kyubisation** [comment]
Should be addressed by #1360
