### ISSUE TITLE
story(sbb-connection-detail): initial implementation

### ISSUE THREAD

**Issue by osminaz** [lyne-design-system/lyne-components#1335]
### Feature Description

**Feature Description**
We want to provide the sbb-connection-detail component. It should render the detail view for one leg of a trip.

[Figma Spec](https://www.figma.com/file/oA9B5W6w0449gtItDzLS86/00%3A-Components?node-id=580%3A556808)

**Design Spec**

- sbb-card mixins for appearance and padding

- layout (happy path):
  - 1. column: depature time -> top; arrival time -> bottom
  - 2. column: vertical pearlChain
  - 3. column: 3 rows:  
       - stop & platform 
       - direction + occupancy 
       - stop & plattform
       

- layout (scary path):
  - case cancelation -> cushim icon with explanation and an "alternative connection" button
  - 1. column: depature time with delay -> top + all cushim icons -> middle + arrival time with delay -> bottom
  - 2. column: vertical pearlChain (situational render)
  - 3. column: 3 rows:  
       - stop & platform + optional: cushim icon with short explanation
       - direction + occupancy
       -  optional: cushim icon with short explanation + stop & plattform

- before start point and after end point there can be a a11y hint
       
 - sbb-divider if contain at least one item (cushim explanations / walkTime) item underneath

**Technical Spec**
- should consume components:
    - sbb-pearl-chain-vertical,
    - sbb-button,
    - sbb-icon,
    - sbb-divider,
    - sbb-timetable-button,
    - sbb-card

- click Event

interface:

```
type legConfig: {
 situations: PtSituation[] (title, detail, priority),
PTRideLeg: {
  start,
  stop,
}
 summary: {
    arrivalStop,
    departureStop, 
    arrival: TimeQuayWrapper,
    arrivalWalk: number, -> out of scope (link notwendig)
    departureWalk: number, -> out of scope (link notwendig)
    departure: TimeQuayWrapper,
    direction: string,
    occupancy: Occupancy,
    product: ServiceProduct,
 }
}
```

markup:
```
 <sbb-connection-detail leg-config={} accessiblity-label="" />
```

### Definition of Done

- [ ] Component is implemented
- [ ] Documentation is provided
- [ ] Tests are implemented
- [ ] E2E Tests are implemented
- [ ] Storybook stories are implemented
- [ ] Navigation via keyboard is tested
- [ ] Screen reader output is tested
- [ ] High-contrast is tested
- [ ] Remaining accessibility is tested
- [ ] UX approved

**Comment by jeripeierSBB** [comment]
Will be tracked/decided in #1901
