### ISSUE TITLE
story(sbb-pearl-chain-vertical): initial implementation

### ISSUE THREAD

**Issue by osminaz** [lyne-design-system/lyne-components#1336]
### Feature Description

**Feature Description**
We want to provide the sbb-pearl-chain-vertical component for the second and third level

[Figma Spec](https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=5439%3A309054)

**Design Spec**

- same as the horizontal sbb-pearl-chain. Except -> not-part-of-the-journey leg

**Technical Spec**
- departure and arrival time is not optional
    
interface:

```
type legConfig: {
 leg: LegDetail[]
}
```

markup:
```
 <sbb-pearl-chain leg-config={} />
```

### Definition of Done

- [ ] Component is implemented
- [ ] Documentation is provided
- [ ] Tests are implemented
- [ ] E2E Tests are implemented
- [ ] Storybook stories are implemented
- [ ] Navigation via keyboard is tested
- [ ] Screen reader output is tested
- [ ] High-contrast is tested
- [ ] Remaining accessibility is tested
- [ ] UX approved

**Comment by jeripeierSBB** [comment]
Will be tracked/decided in #1901
