### ISSUE TITLE
story(sbb-timetable-connection): initial implementation 

### ISSUE THREAD

**Issue by osminaz** [lyne-design-system/lyne-components#1337]
### Feature Description

**Feature Description**
We want to provide the sbb-connection component. It should render the second level

[Figma Spec](https://www.figma.com/file/0pGd1tS4HLCDUf5U1qQpxn/03%3A-Design-%E2%80%93-Home-2.0-Timetable-results?node-id=3349%3A588285)

**Design Spec**

- sbb-card mixins for appearance and padding

**Technical Spec**
- should consume components:
    - sbb-pearl-chain-vertical,
    - sbb-button,
    - sbb-icon,
    - sbb-divider,
    - sbb-timetable-button,
    - sbb-card

interface:

```
type connectionConfig: {
 summaryConfig: summaryConfig,
 situations: PtSituation[],
 legs: Leg[]
 summary: TripSummary,
}
```

markup:
```
 <sbb-connection connection-config={}>
   <sbb-journey-summary summary-config{}/>
   
   this.config.legs.maps(leg => {
    <ul>
      <li><sbb-connection-detai detail-config="" /></li>
    </ul>
   })
   <sbb-connection-legend/>
 </sbb-connection>
```

### Definition of Done

- [ ] Component is implemented
- [ ] Documentation is provided
- [ ] Tests are implemented
- [ ] E2E Tests are implemented
- [ ] Storybook stories are implemented
- [ ] Navigation via keyboard is tested
- [ ] Screen reader output is tested
- [ ] High-contrast is tested
- [ ] Remaining accessibility is tested
- [ ] UX approved

**Comment by jeripeierSBB** [comment]
Will be tracked/decided in #1901
