### ISSUE TITLE
story(sbb-connection-legend): initial implementation 

### ISSUE THREAD

**Issue by osminaz** [lyne-design-system/lyne-components#1338]
### Feature Description

**Feature Description**
We want to provide the sbb-connection-legend component. It should render all situational icons with the message

[Figma Spec](https://www.figma.com/file/oA9B5W6w0449gtItDzLS86/00%3A-Components?node-id=103%3A150879)

**Design Spec**

- layout:

**Technical Spec**
- should consume components:
    - sbb-title,
    - sbb-icon

- iterate all notices and situations and map the icon and the message
    
interface:

```
type legendConfig: {
 situations: PtSituation[]
}
```

markup:
```
 <sbb-connection-legend legend-config={} />
```

### Definition of Done

- [ ] Component is implemented
- [ ] Documentation is provided
- [ ] Tests are implemented
- [ ] E2E Tests are implemented
- [ ] Storybook stories are implemented
- [ ] Navigation via keyboard is tested
- [ ] Screen reader output is tested
- [ ] High-contrast is tested
- [ ] Remaining accessibility is tested
- [ ] UX approved

**Comment by jeripeierSBB** [comment]
Will be tracked/decided in #1901
