### ISSUE TITLE
[Feature request]: Mixin for sbb-badge

### ISSUE THREAD

**Issue by liviakuenzli** [lyne-design-system/lyne-components#1414]
### Request type

Request for a new component

### Functionality

After some discussion we propose to implement the sbb-badge as Mixin (as it's too small & minor to be a component).

### Is there a design proposal?

Yes

### Link to design proposal file (optional)

https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=1300%3A622624

### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Comment by kyubisation** [comment]
The badge is available via the `badge` SCSS mixin.
Please reopen, if the current implementation does not fit your needs.
