### ISSUE TITLE
story(sbb-navigation): open points on the navigation component

### ISSUE THREAD

**Issue by dauriamarco** [lyne-design-system/lyne-components#1523]
### Feature Description

We have a couple of open points to discuss regarding the `sbb-navigation` component:

1. When the navigation is open, should scrolling be disabled on the page behind the backdrop?
2. The behaviour of the navigation on ultra wide needs to be defined, should it keep widening with the page or should it stop growing after reaching the max-width (as in the `sbb-header` component), in that case should it be centered or stick to the left side?

To take in consideration:

- disabling the scroll on the body without shifting the content will cause the scrollbar-track to be still visible on the screen, but it would be "empty", without the scrollbar-thumb;

<img width="1512" alt="disable-scroll" src="https://user-images.githubusercontent.com/101181211/210597718-99a88274-6780-4a04-91c0-c9b640696d23.png">

- it is not possible to keep the content centered on wider layouts without losing the animation of the close button or without repositioning it in the corner of the content (accordingly with the maximum width) and not in the corner of the page.

![max-width-1](https://user-images.githubusercontent.com/101181211/210599660-46b25f7a-1f20-4fb9-8ae3-0a0c896afe2f.png)
![max-width-2](https://user-images.githubusercontent.com/101181211/210599667-021c4af1-c759-4abc-ab0d-ba732c18a893.png)

### Definition of Done

- [ ] Solutions have been discussed

**Comment by mcilurzo** [comment]
ux perspective:
1. When the navigation is open, scrolling in the body should be disabled. visible and empty scrollbar is ok for me.
2. the current implementation ist ok for me.
