### ISSUE TITLE
[Bug]: SBB-Image - aspect-ratio doesn't work as aspected

### ISSUE THREAD

**Issue by christoph-bittmann** [lyne-design-system/lyne-components#1547]
SBB Image allows to define an aspect-ratio. Despite of defining an aspect-ratio with value of "2-1" these image: https://cdn.img.sbb.ch/content/dam/internet/beta/system/error-widget-2.png  won't display with full with and it's are cut off instead:

Screenshot:
![grafik](https://user-images.githubusercontent.com/16793220/213491497-cb8d0550-69c8-4c37-b19e-96cff3149ed8.png)

**Comment by jeripeierSBB** [comment]
Hi @christoph-bittmann, currently we can't reproduce the behavior, can you help us by providing an example with your code?

**Comment by kyubisation** [comment]
Confirmed not to be an issue
