### ISSUE TITLE
Missing part on header buttons onhover

### ISSUE THREAD

**Issue by florianstuerzinger** [lyne-design-system/lyne-components#1569]
Icon and text in the header button should move 1px upwards in the state hover, as is the case with the button.

Figma-Link:
https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=5185%3A306782&t=Xy6SqXbplNZnMUej-1

**Comment by federicoisepponfincons** [comment]
https://github.com/lyne-design-system/lyne-components/pull/1585

pull request opened
