### ISSUE TITLE
The toggle should also fold down when you click on the active part.

### ISSUE THREAD

**Issue by florianstuerzinger** [lyne-design-system/lyne-components#1608]
https://lyne-storybook.app.sbb.ch/?path=/story/components-form-elements-toggle-sbb-toggle--size-m

The toggle should also switch when you click on the active part. 

Examples: 
Google Material: https://material.angular.io/components/slide-toggle/overview
Storybook (see toggles below, under Control): https://lyne-storybook.app.sbb.ch/?path=/story/components-sbb-link--block-xs

**Comment by jeripeierSBB** [comment]
@florianstuerzinger We decided to not implement it in Lyne as it would only be needed for a "hacked" usage and we already define a min-width which is accessible also on mobile screens. So please let it implement by sbb.ch Team. Possible reference: #1625
