### ISSUE TITLE
story(sbb-selection-panel): initial implementation

### ISSUE THREAD

**Issue by jeripeierSBB** [lyne-design-system/lyne-components#1609]
### Feature Description

We want to implement the `sbb-selection-panel`.

[Figma Spec](https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=19036%3A591499&t=VsKz0cgubWpdD0hD-1)

[Figma Usage Example Webshop](https://www.figma.com/file/buijFtfRkVwGmE7A8ySKU9/Webshop-Components?node-id=423%3A99522&t=r2JoFZjj6gVoKKoN-0)

**References**

**Design Spec**

- The `sbb-selection-panel` wraps either a checkbox or a radio button which can optionally toggle a content section.
- It has a card / group like design.
- It has two color variants (white and milk).
- The content section can be opened by checking the checkbox or if radio is selected. Additionally, clicking on all the upper area should set the checked state and therefore open the content. Clicking on the content area does not toggle anything.
- Open and closing of content should be animated.
- Content is optional.
- Checked state is visually represented.
- Focus visible state: https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=19320%3A602111&t=OlJLgLNlP9gHAwld-1

**Important**: The `selection-panel-group` mentioned in Figma, is not a component. Here the `sbb-radio-button-group` and `sbb-checkbox-group` take over this responsibility.

**Technical Spec**

- Check if card or group mixins can be reused.
- Provide a property `@Prop() color: 'white' | 'milk' = 'white';`.
- Provide a slot called "content" which hosts all content which can be expanded.
- Provide a slot called "badge" for `<sbb-card-badge>`
- Provide a `@Prop() forceOpen = false;` to enable that the content section is always visible.
- Provide a `@Prop() disableAnimation = false;` to enable disabled animation.
- Provide events (e.g. `will-open`, `did-open`, `will-close`, `did-close`).
- Disabled state should be read from `<sbb-checkbox>` or `<sbb-radio-button>`.
- For examples in storybook and documentation, apply the 2x gaps in the suffix area
- Ensure `sbb-radio-button-group` and `sbb-checkbox-group` work with the `sbb-selection-panel` (and the `sbb-checkbox` and `sbb-radio-button` elements within).
  - Selection panels should wrap around in the flex context of the groups
  - (Error state should still be correctly reflected, probably nothing has to be changed)
- Extend/refactor `<sbb-checkbox>` and `<sbb-radio-button>` to support being placed in a `<sbb-selection-panel>`
  - For this implement the following slots conditionally (only available/rendered when being placed in a `<sbb-selection-panel>` (content slot included).
    - Provide a slot called "subtext" for the subtext.
    - Provide a slot called "suffix" for the suffix items (no specific styles, consumers should style it by themselves).
    - Disable "icon" slot on `<sbb-checkbox>`

Accessibility:
- Research the best approach to provide an accessible behavior. the upper part should somehow mark that there is a panel and also receive the state e.g. aria-expanded or similar.

Keyboard Navigation: 
- First, the checkbox should receive focus. If there is focusable content below it should receive focus by pressing tab key.
- When closed, the focusable elements inside the content should not receive focus/should not be "tab-able"

Radio example:
```html
<sbb-radio-button-group>
  <sbb-selection-panel>
    <sbb-card-badge slot="badge"></sbb-card-badge>
     <sbb-radio-button>
       Value
       <span slot="subtext">Subtext</span>
       <span slot="suffix">
         <sbb-icon/>
         <span class="sbb-text-xs sbb-text--bold">CHF</span>
         <span class="sbb-text-m sbb-text--bold">40.00</span>
       </span>
     </sbb-radio-button>
     <div slot="content">
      Inner Content
     </div>
  </sbb-selection-panel>
</sbb-radio-button-group>
```

Checkbox example:
```html
<sbb-checkbox-group>
  <sbb-selection-panel>
    <sbb-card-badge slot="badge"></sbb-card-badge>
     <sbb-checkbox>
       Value
       <span slot="subtext">Subtext</span>
       <span slot="suffix">
         <sbb-icon/>
         <span class="sbb-text-xs sbb-text--bold">CHF</span>
         <span class="sbb-text-m sbb-text--bold">40.00</span>
       </span>
     </sbb-checkbox>
     <div slot="content">
      Inner Content
     </div>
  </sbb-selection-panel>
</sbb-checkbox-group>
```

### Definition of Done

- [x] Component is implemented
- [x] Documentation is provided
- [x] Tests are implemented
- [x] E2E Tests are implemented
- [x] Storybook stories are implemented
- [x] Navigation via keyboard is tested
- [x] Screen reader output is tested
- [x] High-contrast is tested
- [x] Remaining accessibility is tested
- [x] UX approved

**Comment by mcilurzo** [comment]
focus state: https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=19320%3A602111&t=OlJLgLNlP9gHAwld-1
