### ISSUE TITLE
[A11y] more aria props for sbb-card ♿

### ISSUE THREAD

**Issue by osminaz** [lyne-design-system/lyne-components#1611]
We need for example the aria-expanded attribute to show Screenreaders that something happend in the dom/screen.

It seems like that you can't use this attribute on the Host element. So I would assume that it have to forwarded directly to the button element with a prop.

**Comment by jeripeierSBB** [comment]
@osminaz Did you try to set role=„button“ on the host (sbb-card) in combination with aria expanded?

**Comment by osminaz** [comment]
@jeripeierSBB good to know. this works. But the screenreader reads it like: "...Schalter Schalter erweitert." I'm not if this is good enough.

**Comment by jeripeierSBB** [comment]
@osminaz Which screenreader and browser do you use?

**Comment by osminaz** [comment]
@jeripeierSBB NVDA (win10)
