### ISSUE TITLE
[Feature Request]: sbb-icon - additional badge prop

### ISSUE THREAD

**Issue by osminaz** [lyne-design-system/lyne-components#1613]
According to this [figma section](https://www.figma.com/file/oA9B5W6w0449gtItDzLS86/00%3A-Components?node-id=2412%3A345374&t=5JAGjksSsRSQeaMe-0) we need an option to add a badge to an exicting icon.

Alternative:

introduce a new controls-tick-small icon like: [controls-x-small](https://www.figma.com/file/UQBd7cHKav0hr9oXYp7opJ/SBB-Icons?node-id=372%3A1866&t=ecjSyCjvPPAlLpHU-0)

**Comment by jeripeierSBB** [comment]
Hi @osminaz, after talking to @mcilurzo and @kyubisation we decided to not implement anything in this case in lyne. It is a very rare pattern which should not be re-used. However, in the meanwhile we fixed the badge mixin so you can use it now :).
