### ISSUE TITLE
Incorrect appearance of the scrollbar in different browsers

### ISSUE THREAD

**Issue by mcilurzo** [lyne-design-system/lyne-components#1627]
## Preflight Checklist
- [x] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Which package(s) are you using?
- [x] `lyne-components`
- [ ] `non package issue`

## Environment
Browser / browser: See the screens in Figma.

## Detailed description
The scrollbar is displayed differently horizontally and vertically in many browsers. See the screens in Figma.

## Steps to reproduce the issue
1. open beta.sbb.ch
2. choose a connection, e. g. bern to luzern, verkehrshaus
3. choose a trip with a train formation
4. choose a section with a train formation, e. g. luzern to luzern verkehrshaus
5. click on "auf Karte" anzeigen

## Additional information
Figma link: https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=19351%3A602457&t=OlJLgLNlP9gHAwld-1

**Comment by kyubisation** [comment]
We could add a story in storybook to demonstrate and test the scrollbars
