### ISSUE TITLE
[Bug]: sbb-train-formation - semantic HTML and a11y

### ISSUE THREAD

**Issue by osminaz** [lyne-design-system/lyne-components#1638]
We got few feedback for the sbb-train-formation:

- If there no attribute icons or occupancy icons, there is still some markup or some text for screenreader
- the whole component should be a list where a sbb-wagon should be a list item
- the label for sector and direction are currently a h3. (should be lower or customizable)

![image](https://user-images.githubusercontent.com/105784969/220693378-b4727d20-8149-4bd7-b7ec-bed134e0425e.png)

**Comment by kyubisation** [comment]
@osminaz The first point is not clear enough to us. Could you elaborate on "some markup or some text for screenreader"?
