### ISSUE TITLE
[Bug]: SbbTrainFormation - direction ignored by SR

### ISSUE THREAD

**Issue by WalkingOS** [lyne-design-system/lyne-components#1771]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.33.10

### Operating system

Windows 10

### Browser / Browser version

Chrome

### Input mode

Mouse/Keyboard

### What happened?

Screenreaders ignores the direction of the train (Tested with nvda and voiceover)

### Steps to reproduce the issue

1. Navigate trought the train-formation with the arrow keys

**Comment by jeripeierSBB** [comment]
Probably we need to re introduce a heading again which level has to be configured from outside.
