### ISSUE TITLE
story(sbb-accordion): initial implementation

### ISSUE THREAD

**Issue by DavideMininni-Fincons** [lyne-design-system/lyne-components#1818]
### Feature Description

We want to implement the accordion components.

[Figma Spec](https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=140%3A5&t=olA4VPN5utOO8jvQ-1)

**References**

- https://angular.app.sbb.ch/angular/components/accordion/overview
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details
- https://www.w3.org/WAI/ARIA/apg/patterns/accordion/examples/accordion/
- https://material.angular.io/components/expansion/overview
- https://www.figma.com/file/BS4MP1EC7Fb22MgcWtwlOX/07%3A-Design-%E2%80%93-%C3%96V-Guthaben?type=design&node-id=8828-407623&t=ym0PljdRZvyO0A05-0

**Design Spec**

- The accordion can be a single expansion panel or a group of expansion panels.
- The first expansion panel in a group should have the upper corners rounded
- The last expansion panel in a group should have the lower corners rounded
- A singular expansion panel should have all corners rounded
- Should have open and close animation

**Technical Spec**

The implementation should be done in three components: `<sbb-expansion-panel>`, `<sbb-expansion-panel-header>` and `<sbb-accordion>`.
The `<sbb-expansion-panel>` can be used without a `<sbb-accordion>` (See example below).

`<sbb-expansion-panel>`:

- Should have property `level?: '1' | '2' | '3' | '4' | '5' | '6'`, which is internally used to wrap the header in either a div (not set) or `h{level}`
- Should have property `expanded = false` to open the expansion panel
- Should have property `disabled = false` (@mcilurzo To be discussed)
- Should have named slot for `sbb-expansion-panel-content`
- Should have named slot for header
  - See level description above
- add a prop to disable open/close animation: `@Prop({ reflect: true }) public disableAnimation = false;`
- two color background variant (see sbb-selection-panel): `@Prop() public color: 'white' | 'milk' = 'white';`
- combination of did/will & open/close events as in many other components

`<sbb-expansion-panel-header>`:

- Should be a button implementation, with aria-expanded and aria-controls referencing the content
- Should have property `iconName?: string` and slot `icon` to optionally display an icon

`<sbb-expansion-panel-content>`:

- No function (set its own id)

`<sbb-accordion>`:

- Should have property `level?: '1' | '2' | '3' | '4' | '5' | '6'`, which is applied/inherited by nested `<sbb-expansion-panel>`
- Should have property `multi = false`, which allows multiple expansion panels to be open at the same time. Per default only one expansion panel in a `<sbb-accordion>` can be open.

```html
<sbb-expansion-panel>
  <sbb-expansion-panel-header> This is the expansion title </sbb-expansion-panel-header>
  <sbb-expansion-panel-content>This is the primary content of the panel.</sbb-expansion-panel-content>
</sbb-expansion-panel>

<sbb-accordion>
  <sbb-expansion-panel>
    <sbb-expansion-panel-header> Header 1 </sbb-expansion-panel-header>
    <sbb-expansion-panel-content>Content 1</sbb-expansion-panel-content>
  </sbb-expansion-panel>
  <sbb-expansion-panel>
    <sbb-expansion-panel-header> Header 2 </sbb-expansion-panel-header>
    <sbb-expansion-panel-content>Content 2</sbb-expansion-panel-content>
  </sbb-expansion-panel>
</sbb-accordion>
```

### Definition of Done

- [ ] Component is implemented
- [ ] Documentation is provided
- [ ] Tests are implemented
- [ ] E2E Tests are implemented
- [ ] Storybook stories are implemented
- [ ] Navigation via keyboard is tested
- [ ] Screen reader output is tested
- [ ] High-contrast is tested
- [ ] Remaining accessibility is tested
- [ ] UX approved

**Comment by DavideMininni-Fincons** [comment]
Check both sbb-accordion and sbb-accordion-item

sbb-accordion-item
- Icon at left: `@Prop() public iconName?: string;`
- Title: can we use `@Prop() public titleContent?: string;` & `@Prop() public titleLevel?: InterfaceTitleAttributes['level’];` ?
- Toggle: `chevron-small-up`/`down` icon instead than current SVG?
- Add a disableAnimation property
- Events: willOpen/didOpen/willClose/didClose ?
- Reuse SbbOverlayState ?
- Two variants (default/milk)? What state is 'Opacity 80%'?
- Animation?

sbb-accordion
- Keep the onlyOneOpen logic?

**Comment by kyubisation** [comment]
@DavideMininni-Fincons Could I ask you to take a look at https://angular.app.sbb.ch/angular/components/accordion/overview and write a specification along that use case? I apologize for only mentioning this now.
