### ISSUE TITLE
story: reorder and tidy up Storybook component list

### ISSUE THREAD

**Issue by federicoisepponfincons** [lyne-design-system/lyne-components#1829]
### Feature Description

We would like to reduce the chaos inside the storybook component list, by moving and reordering current stories into groups that share the same component base.

e.g. `sbb-menu` and `sbb-menu-action` should stay in the same group `sbb-menu`, with all the others of the same kind.

Documentation should be moved and merged too, from the single component story to the main one.

TODOs:
- Group elements as folders and don't move anything to internal
- Also flatten form elements and group similar to what is suggested below
- Leave internals
- Move timetable to its own top level category, similar to "components", "styles", etc.
- Adapt order in preview.js

### Component list (TBD)

- [x] `sbb-accordion` (contains `sbb-accordion-group` + `sbb-accordion`)
- [x] `sbb-alert` (contains `sbb-alert-group` + `sbb-alert`)
- [x] `sbb-button`
- [x] `sbb-card` (contains `sbb-card-badge` + `sbb-card`)
- [x] `sbb-chip`
- [x] `sbb-clock`
- [x] `sbb-dialog`
- [x] `sbb-divider`
- [x] `sbb-footer`
- [x] `sbb-group`
- [x] `sbb-header` (contains `sbb-header-action` + `sbb-header`)
- [x] `sbb-icon`
- [x] `sbb-image`
- [x] `sbb-journey-header`
- [x] `sbb-link`
- [x] `sbb-link-list`
- [x] `sbb-skiplink-list`
- [x] `sbb-logo`
- [x] `sbb-map-container`
- [x] `sbb-menu` (contains `sbb-menu-action` + `sbb-menu`)
- [x] `sbb-navigation` (contains `sbb-navigation-action` + `sbb-navigation-list` + `sbb-navigation-marker` + `sbb-navigation-section` + `sbb-navigation`)
- [x] `sbb-selection-panel`
- [x] `sbb-signet`
- [x] `sbb-tab` (contains `sbb-tab-group` + `sbb-tab-title`)
- [x] `sbb-tag` (contains `sbb-tag-group` + `sbb-tag`)
- [x] `sbb-teaser` (contains `sbb-teaser-hero` + `sbb-teaser`)
- [x] `sbb-title`
- [x] `sbb-tooltip` (contains `sbb-tooltip-trigger` + `sbb-tooltip`)
- [x] `form-elements`
- [x] `timetable`

**Comment by jeripeierSBB** [comment]
In my opinion we need to discuss this topic as there are various issues with the idea:
 - Merging storybook...
   - ...increases complexity of storybook files which makes them more difficult to understand from user perspective and more difficult to handle from our side.
   - ...will increase costs for Chromatic drastically, as we can't use the story collection anymore for a lot of stories (e.g. in sbb-menu you have play stories but if also all stories of the sbb-menu-action will be included (which now inly cost 7 snapshots in Chromatic) then you will have a lot more snapshots (e.g. for 5 stories of sbb-menu-action you will then have 5*7 snapshots).
- Automatic API documentation will not be useful anymore as all child components API don't show up e.g. in the group component.

In my opinion we shouldn't do this story but either create a separate documentation platform manually (e.g. https://lyne.sbb.ch) or rely on UX documentation (https://digital.sbb.ch). Storybook is also meant as kind of visual unit testing for each component or child component and not to be a full documentation platform.

As a light improvement we can maybe in child components better point to group components or vice versa so it's clearer in documentation to where something belongs.

**Comment by kyubisation** [comment]
Discussed via Teams with @jeripeierSBB. Currently preferred solution would be to group the relevant components in a folder together and not to move any components to internal.
