### ISSUE TITLE
[Feature request]: Date-picker with month and year selection

### ISSUE THREAD

**Issue by LorenzHofmann** [lyne-design-system/lyne-components#1873]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### It affects the following packages

Components

### Functionality

**Date-picker with month and year selection**

An extension of the Date-picker component is needed to make the input of the the date of birth in the traveler entry more attainable.

Extension of the component by:
- Choice of year
- Choice of month

### Link to design proposal file

https://www.figma.com/proto/SIDC01QZs303UVcYIIQnrB/50-Lyne-oder-nicht-Lyne?page-id=14%3A14172&type=design&node-id=16-40230&viewport=681%2C-353%2C1.6&t=SyqGTYZ9bvFOUiqU-1&scaling=min-zoom&starting-point-node-id=16%3A40230

**Comment by kyubisation** [comment]
Hello @LorenzHofmann 
I have created the corresponding story for your request: #1883
Having separate clicking targets for year and month is not feasible in my eyes, as there might not be enought space depending on localization.
But I think something like the Material Datepicker is a solution that works just as well.
