### ISSUE TITLE
bug(a11y): sbb-navigation can be left with screenreader without closing A4A#77

### ISSUE THREAD

**Issue by kyubisation** [lyne-design-system/lyne-components#1879]
The main navigation can be exited using the screen reader without closing it.
With screen readers you can use the arrow keys to reach the whole page when the navigation is open.

**Comment by jeripeierSBB** [comment]
showModal() probably becomes usable in Webkit / Safari: https://github.com/WebKit/WebKit/commit/6bad1368d570fc5da254bf01d97d7032c44d272d

**Comment by jeripeierSBB** [comment]
Will be in Safari 17: https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes
