### ISSUE TITLE
[Bug]: floating-label in sbb-form-field not working using sbb-dialog

### ISSUE THREAD

**Issue by Ckauczor** [lyne-design-system/lyne-components#1884]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Design Tokens

### Which version of Lyne Components are you using

0.37.11

### Operating system

Win 10

### Browser / Browser version

Chrome 114.0.5735.134

### Input mode

Mouse/Keyboard

### What happened?

when reopen a dialog floating-input is not visible in sbb-form-fields

### Steps to reproduce the issue

open dialog with fields
then open another dialog window

**Comment by jeripeierSBB** [comment]
My findings:
- for select: whenever displayvalue changes, it should somehow notify the form field about the change
- for all other input types: formfield should have a reset() method where state of floating label gets reset
- maybe it's possible to listen to form reset event in a way
