### ISSUE TITLE
[Bug]: sbb-datepicker-previous/next-day can't be disabled

### ISSUE THREAD

**Issue by k-luise** [lyne-design-system/lyne-components#1892]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Design Tokens

### Which version of Lyne Components are you using

0.37.3

### Input mode

None

### What happened?

When setting the disabled property manually on sbb-datepicker-previous/next-day, clicking is still possible and date changes happen.
The < > icons only look disabled.

### Steps to reproduce the issue

1. Set up the datepicker with sbb-datepicker-previous-day and sbb-datepicker-next-day
2. disable sbb-datepicker-previous-day
3. click it

**Comment by kyubisation** [comment]
We decided internally to remove the disabled property for now, as the use case is tightly coupled to the datepicker.
