### ISSUE TITLE
story(sbb-teaser): redesign of the standard teaser + code clean-up

### ISSUE THREAD

**Issue by kyubisation** [lyne-design-system/lyne-components#1897]
### Feature Description

The sbb-teaser standard (not the Hero or the Panel) has been redesigned in [Figma](https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=434-494616&mode=design&t=Wx5uUMETuK4asVOS-0)

- sbb-chip has to be included as optional element in the text part
- there are 3 variants related to the text position: right-top, right-centered, bottom-left
- hover state: see variations in Figma
- the user should set the size of the picture (width) used and the image ratio
- however there should be default values for image width (300px`*`) and aspect-ratio (4:3)
- the text block can exceed the height of the image, therefore the smaller block should vertically align (in the right-centered variant)
- the tab focused variant is also provided in Figma

`*` _default image width is a temporary value, should be defined in the next days by_ @mcilurzo 

Also the component code has various legacy properties (e.g. hug) and is not labelled properly, therefore it needs a clean-up.

### Definition of Done

- [x] New design variant is implemented
- [x] Documentation is updated
- [x] Tests are updated
- [x] Navigation via keyboard is tested
- [x] Component uses appropriate properties
- [x] Component is documented/labelled
- [x] UX approved

**Comment by jeripeierSBB** [comment]
@mcilurzo Hello :)

**Comment by mcilurzo** [comment]
proposal (to discuss): https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=20312%3A607994&mode=design&t=CXbzTiposN3YUHge-1

**Comment by mcilurzo** [comment]
ready for implementation
