### ISSUE TITLE
[Feature request]: Notification content only

### ISSUE THREAD

**Issue by florianstuerzinger** [lyne-design-system/lyne-components#1905]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### It affects the following packages

Components

### Functionality

Request for a content-only variant of the component notification. It is important to consider whether it should be a variant of the Lyne Notification or whether it should be created as a separate project component.

### Link to design proposal file

https://www.figma.com/file/9Cdo8bGTUtBSR2am6O4fHl/Notification-content-only?type=design&node-id=9201%3A375735&mode=design&t=6UgGCYvd0fp8Xcxj-1

**Comment by jeripeierSBB** [comment]
Discussion with @mcilurzo -> different component, something like "sbb-hint". to be challenged with @florianstuerzinger

**Comment by mcilurzo** [comment]
proposal in figma: https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=26122%3A501619&mode=design&t=qhk605TgsdvxvovG-1

**Comment by jeripeierSBB** [comment]
Will be continued in #1932
