### ISSUE TITLE
[Feature request]: Redesign of tabs

### ISSUE THREAD

**Issue by florianstuerzinger** [lyne-design-system/lyne-components#1907]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### It affects the following packages

Components

### Functionality

The tab component is redesigned to better distinguish it from the tags and buttons. Target image is shown in Figma in a Branch:
https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/branch/wGheg6gpTypsswasB0YvEI/Lyne-Components?type=design&node-id=25991%3A455064&mode=design&t=XwZWIlStuex0GumJ-1

A prototype was created to show the behaviour (animation, pagination, ...):
https://www.figma.com/proto/9r6xSfNmEfCFxl1yFYedrj/branch/wGheg6gpTypsswasB0YvEI/Lyne-Components?type=design&page-id=459%3A502393&node-id=25974-493070&viewport=1288%2C-362%2C0.25&t=QU45eySZi0rqExCi-1&scaling=scale-down&starting-point-node-id=25974%3A493070&mode=design

### Link to design proposal file

https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/branch/wGheg6gpTypsswasB0YvEI/Lyne-Components?type=design&node-id=25991%3A455064&mode=design&t=XwZWIlStuex0GumJ-1

**Comment by mcilurzo** [comment]
ready for implementation: 
https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=529%3A550879&mode=design&t=HkbLxKBYuRXuSLTX-1
