### ISSUE TITLE
story(sbb-container, sbb-sticky-bar): initial implementation

### ISSUE THREAD

**Issue by florianstuerzinger** [lyne-design-system/lyne-components#1908]
We want to implement a container component and associated sticky bar.
The container component has the same spacing behavior as the header and footer (including the `expanded` property).

[Figma Spec](https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=25018%3A468481&mode=design&t=MDGURDdCkcBSQrfL-1)

**References**

- https://www.figma.com/proto/HeBonE3QY13ABQ4f2FShTJ/lyne-projects?page-id=0%3A1&type=design&node-id=2-182675&viewport=1321%2C1370%2C0.32&t=Kaic1GfC9eEVmjNn-1&scaling=min-zoom

**Design/Technical  Spec**

`<sbb-container>`

- Have the same spacing as `<sbb-header>` and `<sbb-footer>`, including a `expanded` property
- Use the sass mixin for spacing as is used in header and footer

`<sbb-sticky-bar>`

- Can be slotted into `<sbb-container>` and assumes its horizontal spacing
- Should stick to the bottom, while the container is visible
- Should have a upper shadow when it is sticky at the bottom
- Logic for the shadow should be self-contained in the `<sbb-sticky-bar>` (if possible)
- Sticky at the top is out-of-scope at the moment

```html
<sbb-container>
  my content
</sbb-container>

// sticky bar
<sbb-container>
  my content
  <sbb-sticky-bar>
    sticky content
  </sbb-sticky-bar>
</sbb-container>
```

---

_Original request_

### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for a new component

### It affects the following packages

Components

### Functionality

The bar should be created including the transition of the stickyness into the content. The content of the sticky bar is a placeholder. It is important that the spacing below the placeholder in the embedded state is subtracted from the section spacing that follows.

### Link to design proposal file

https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=25018%3A468482&mode=design&t=t3CgF6sOkvbr2UNz-1

**Comment by mcilurzo** [comment]
ready for implementation
