### ISSUE TITLE
[Feature request]: Status

### ISSUE THREAD

**Issue by florianstuerzinger** [lyne-design-system/lyne-components#1932]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for a new component

### It affects the following packages

Components

### Functionality

A status component is needed. It comes in two characteristics, short and extended and in two versions, info and error. 

### Link to design proposal file

https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=16667%3A499387&mode=design&t=llEG1lwBwR3fcaeD-1

Current: https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=16660%3A499382&mode=dev

## Specification

- Compare with `sbb-notification`
- Have property `@property({ reflect: true }) public type?: 'info' | 'success' | 'warn' | 'error' = 'info';`
- Have an unnamed slot for text
- Have a property `title-content` and a named slot `title`
- Icons are set by default for each type, and cannot be changed

```html
<sbb-status type="success">
  <span slot="title">Title</span>
  Text
</sbb-status>
```

**Comment by jeripeierSBB** [comment]
@mcilurzo Can you check if this according to you is ready to technically spec / implement?

**Comment by mcilurzo** [comment]
@jeripeierSBB yes, it seems ready: https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=16667%3A499387&mode=design&t=nYUutU6X1xzVW8Uc-1
