### ISSUE TITLE
story(sbb-navigation): use divider to divide navigation from section which will have some color changes

### ISSUE THREAD

**Issue by jeripeierSBB** [lyne-design-system/lyne-components#1934]

**Comment by jeripeierSBB** [comment]
final decision of @mcilurzo needed. If there is a "go", please move it to "next" column

**Comment by mcilurzo** [comment]
fixed in figma: https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=869%3A627065&mode=design&t=2GGztNcWeqEAA28T-1
