### ISSUE TITLE
[Bug]: When adding a datepicker to an sbb-card the calendar is not showing up

### ISSUE THREAD

**Issue by blauenersbb** [lyne-design-system/lyne-components#1982]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

40.2

### Operating system

Mac OS

### Browser / Browser version

Chrome

### Input mode

None

### What happened?

When adding a datepicker to an sbb-card the calendar is not showing up after clicking on the tooltip toggle (calendar icon).
We figured out, that the "transform" property on the "sbb-card__wrapper" is responsible for this.
![Screenshot 2023-09-13 at 12 32 31](https://github.com/lyne-design-system/lyne-components/assets/144141244/7bf60827-c5a2-4c4a-912c-48aac7531289)
![Screenshot 2023-09-13 at 12 32 42](https://github.com/lyne-design-system/lyne-components/assets/144141244/d641d714-971e-4789-b54e-6467ab14e590)

### Steps to reproduce the issue

1. Add a datepicker to an sbb-card component
2. Click the tooltip-toggle icon
3. Notice that the calendar does not show up

**Comment by jeripeierSBB** [comment]
As a first fix we can remove transform for static card as it is not used anyways.
