### ISSUE TITLE
[Bug]: Sbb-header-action extra attributes in react environment Warning

### ISSUE THREAD

**Issue by Ckauczor** [lyne-design-system/lyne-components#1992]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.40.11

### Input mode

None

### What happened?

When opening the dev console from webshop-offers-frontend repo, we see that error:
Warning: Extra attributes from the server: aria-haspopup,aria-controls,aria-expanded,data-expanded,role,dir,tabindex,class
    at sbb-header-action
    
That is our implementation:
```
<SbbHeader className="hidden-until-hydrated" hideOnScroll>
        <SbbHeaderAction id="nav-trigger" iconName="hamburger-menu-small" expandFrom="small">
          {t('global.menu')}
        </SbbHeaderAction>
...
```

### Steps to reproduce the issue

1) checkout webshop-offers-frontend
2) npm i
3) npm run dev
4: open localhost:3100

### Relevant log output

```shell
Warning: Extra attributes from the server: aria-haspopup,aria-controls,aria-expanded,data-expanded,role,dir,tabindex,class
    at sbb-header-action
```

**Comment by kyubisation** [comment]
Hello @Ckauczor 
Is this currently deployed somewhere?

**Comment by Ckauczor** [comment]
> Hello @Ckauczor Is this currently deployed somewhere?

it is on https://dev-www.sbb.ch/offers/de/offers. But the warning appears only on local environment. (NextJS/React)

**Comment by kyubisation** [comment]
According to multiple search results, this seems to be caused by local browser extensions. Can you confirm whether this is the case (e.g. incognito window or different browser)?

**Comment by kyubisation** [comment]
This might also be related to the component being a web component, in which case there is nothing we could do, as our React wrapper does not contain logic/configuration that could fix this.

**Comment by kyubisation** [comment]
Related: https://legacy.reactjs.org/docs/dom-elements.html#suppresshydrationwarning

**Comment by Ckauczor** [comment]
Hi @kyubisation,
i made the following changes to fight the missing attributes. The only one problem is "tabIndex" in Sbb-Header-Action Component

it will be rendered as "tab-index", is it possible for that case just to add "tabindex" as prop to the component?

`<SbbHeaderAction id="nav-trigger" iconName="hamburger-menu-small" expandFrom="small" data-testid="menueopen" aria-controls="sbb-navigation-1" aria-expanded={false} 
          aria-haspopup="menu" role="button" dir="ltr" class="hydrated" data-expanded="" tabIndex={0}>
          {t('global.menu')}
        </SbbHeaderAction>`

**Comment by kyubisation** [comment]
Not directly, because that is an existing property of HTML.
Just using `tabindex` does not work? Is that an error in JSX?

**Comment by Ckauczor** [comment]
no it will result in an error when i use `tabindex` in .tsx

**Comment by kyubisation** [comment]
Discussed with @Ckauczor via Teams.
We cannot (yet) easily add tabIndex to our components and it is not clear, what React is doing with `tabIndex` conversion to `tab-index`, which is incorrect. @Ckauczor will analyse why that is the case.

**Comment by Ckauczor** [comment]
will be fixed hopefully with integration of lit
