### ISSUE TITLE
[Bug]: SBB-Toggle-Option Selector switch is output with misleading info

### ISSUE THREAD

**Issue by Ckauczor** [lyne-design-system/lyne-components#2014]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.40.14

### Input mode

None

### What happened?

Tooltip-Handling // Radio button is output with misleading information (submenu) because the element is marked with aria-haspopup="dialog" attribute although there is no submenu.

![Unbenannt](https://github.com/lyne-design-system/lyne-components/assets/72215879/91c34482-62d3-4f4a-88f8-fa25621b3dd3)

### Steps to reproduce the issue

1. Step one
2. Step two
3. ...

**Comment by jeripeierSBB** [comment]
Will probably be addressed when we refactor the tooltip in general way.

**Comment by Ckauczor** [comment]
hey @jeripeierSBB, "aria-expanded, aria-controls, aria-haspopup" can be removed in sbb-toggle-option because it's not necessary for screenreader users.

**Comment by jeripeierSBB** [comment]
Hi @Ckauczor, these properties are coming from the tooltip, not from the toggle-option itself. The "problem" is that you bound the tooltip to the toggle option (?).
As said, we will completely refactor the sbb-tooltip and therefore hopefully get around this. Maybe it's not best practice to use tooltip on toggle itself, or how do you provide solutions to mobile users?

**Comment by Ckauczor** [comment]
Hi, i could confirm that you are right :) we remove the tooltips and the aria-labels are gone
