### ISSUE TITLE
[Bug]: After closing the dialog via submit the focus order is not correct

### ISSUE THREAD

**Issue by Ckauczor** [lyne-design-system/lyne-components#2016]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.40.14

### Input mode

None

### What happened?

After the dialog window "Edit travelers" is closed via the Apply button, the card "Single trip" is displayed. However, this card is skipped when navigating further with the Tab key. Because the card is not arranged in the correct order in HTML.
In the dialog, after editing a traveler, the focus is not set to the next traveler, but to the "Add Traveler" button. Consequently, keyboard users have to navigate backwards to reach the other traveler.

Recommendation
After closing dialogs, the focus should sit on the triggering element so that navigation can continue coherently.
![13](https://github.com/lyne-design-system/lyne-components/assets/72215879/074387a0-13a0-4d91-aee4-b445880899fd)

### Steps to reproduce the issue

1. Step one
2. Step two
3. ...

**Comment by kyubisation** [comment]
Hello @Ckauczor 
The `<sbb-dialog>` already sets the focus after closing the dialog to the trigger.
Additionally, please provide a reproduction or a link so we can research the issue further.

**Comment by Ckauczor** [comment]
we found an easy solution for setting back the focus on the initial element.
Thanks @kyubisation
