### ISSUE TITLE
[Bug]: Status of checkboxes is not correct - aria-tag expanded-label

### ISSUE THREAD

**Issue by Ckauczor** [lyne-design-system/lyne-components#2017]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Design Tokens

### Which version of Lyne Components are you using

0.40.14

### Input mode

None

### What happened?

The City Ticket checkboxes are output with the misleading status of "reduced".

The misleading "reduced" status should be removed from the element.
![23](https://github.com/lyne-design-system/lyne-components/assets/72215879/205a9fb7-21ac-43cd-9f85-b83210d52ae7)

### Steps to reproduce the issue

1. Step one
2. Step two
3. ...

**Comment by kyubisation** [comment]
We are setting this text in https://github.com/lyne-design-system/lyne-components/blob/master/src/components/sbb-checkbox/sbb-checkbox.tsx#L281-L283 and https://github.com/lyne-design-system/lyne-components/blob/master/src/components/sbb-radio-button/sbb-radio-button.tsx#L249-L252
We should check, whether the current checkbox/radio button is the primary checkbox/radio button and only then add this text.
