### ISSUE TITLE
[Bug]: SBB-Dialog Content is not scrollable / accessible

### ISSUE THREAD

**Issue by Ckauczor** [lyne-design-system/lyne-components#2019]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.40.14

### Input mode

None

### What happened?

With the high font magnification (400%), the pages are not scrollable, so the application cannot be operated.
![zoom](https://github.com/lyne-design-system/lyne-components/assets/72215879/b3d0a560-1d03-46ba-b084-4cce1bb1c2f3)

### Steps to reproduce the issue

1. Step one
2. Step two
3. ...

**Comment by kyubisation** [comment]
I discussed this with @mcilurzo. We are thinking about reducing the title size/visual level.
However, additionally you could use the purely horizontal `<sbb-action-group>` here, which would heavily improve the current state.
