### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lauracazansbb** [lyne-design-system/lyne-components#2193]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

^0.42.4

### Operating system

windows 10

### Browser / Browser version

chrome

### Input mode

Mouse/Keyboard

### What happened?

Problem is at the component -sbb-selection-panel--with-checkbox-checked-disabled.
![image](https://github.com/lyne-design-system/lyne-components/assets/150944986/4b09d729-8331-4cf1-a36e-f41068cfe487)

The border of the deactivated selection field should be lighter, even if it is selected. The cause is that for panels without content the style for the border is not set.

![Screenshot1](https://github.com/lyne-design-system/lyne-components/assets/150944986/1d4fbecf-eb4c-4237-8e5b-1f454bb42075)

### Steps to reproduce the issue

1. acces https://int-www.sbb.ch/de/billette-angebote/abos/halbtax-plus/angebot.html
2. Log in
3. observe the ÖV-Guthaben package

**Comment by jeripeierSBB** [comment]
Fixed by #2189 . Will be released with new Lit implementation of our components
