### ISSUE TITLE
[Bug]: Alert in SBB Dialog not accessible

### ISSUE THREAD

**Issue by Ckauczor** [lyne-design-system/lyne-components#2195]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.42.1

### Input mode

Mouse/Keyboard

### What happened?

The error message in SBB alert "Please select at least one person / dog / bicycle." in the "Travellers" dialog cannot be accessed with the screen reader. Therefore it is not noticeable for screen reader users.

Recommendation:

The message should not be hidden by the screen reader. (it should be accessible with the arrow keys)
The message should also be recognized and issued automatically. (aria-live="polite")
![image-2023-11-15-10-41-48-170](https://github.com/lyne-design-system/lyne-components/assets/72215879/8fa91b50-97ff-4dc7-92a4-da7285800570)

### Steps to reproduce the issue

1. Step one
2. Step two
3. ...

**Comment by jeripeierSBB** [comment]
Hi @Ckauczor, our notification is just a layout component. It's the responsibility of the consumers to add aria-live regions if needed. Without an exact replication, I can't say why it's not accessible by arrow keys. At least in our showcase I can access it by arrow keys (as said we do nothing regards accessibility, it's just layout).
