### ISSUE TITLE
docs: every storybook story should work when used in Docs section

### ISSUE THREAD

**Issue by jeripeierSBB** [lyne-design-system/lyne-components#2269]
e.g. in when using select examples in "Docs" section, it's broken. With this story, every story should be checked.
 
 - remove any document.getElementById or other id reference and try to use relative references
 - ?

**Comment by TomMenga** [comment]
Update:
The only remaining problems are those relative to the positioning of the autocomplete and the select overlay panel. The other overlays work fine
