### ISSUE TITLE
Self referential @use URLs

### ISSUE THREAD

**Issue by thepian** [lyne-design-system/lyne-components#2307]
https://github.com/lyne-design-system/lyne-components/blob/2196fda52f53b09de5e75db4b6541bfb240b001f/src/components/core/styles/core/mediaqueries.scss#L5

There is at least one import which refers to distributions files in an odd way.

`@use 'node_modules/@sbb-esta/lyne-design-tokens/dist/scss/sbb-variables.scss' as sbb-tokens;`

Hopefully a better way can be found to include this.

Perhaps `@use '~@sbb-esta/lyne-design-tokens/dist/scss/sbb-variables.scss' as sbb-tokens;` or
`@use '~lyne-design-tokens/dist/scss/sbb-variables.scss' as sbb-tokens;`.

When running webpack from a working directory other than the one for the project, the compilation blows up because the sass-loader cannot find sub-variables.scss.
I have to fix this by creating an alias for the import.

**Comment by jeripeierSBB** [comment]
Thanks for the issue.
Your two suggestions did not work (at least not out of the box, maybe I need to adjust some config).
But there was another one which works: `@use '@sbb-esta/lyne-design-tokens/dist/scss/sbb-variables.scss' as sbb-tokens;`. Do you think this would be an improvement for your situation? But I'm not sure if I maybe break something else :P
