### ISSUE TITLE
[Bug]: Windows HCM show sbb-select placeholder twice

### ISSUE THREAD

**Issue by Ckauczor** [lyne-design-system/lyne-components#2326]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.42.6

### Operating system

Win 10

### Input mode

None

### What happened?

When using sbb-select in sbb-form-field and setting placeholder, there is an visual bug in windows High Contrast Mode.

it shows the floating-label of the form-field and additional the placeholder.

### Steps to reproduce the issue

1. Step one
2. Step two
3. ...

**Comment by DavideMininni-Fincons** [comment]
Link: https://lyne-storybook.app.sbb.ch/?path=/story/components-sbb-select--borderless&args=floatingLabel:!true

![Image](https://github.com/lyne-design-system/lyne-components/assets/101575400/6e76e58c-d7ba-4519-aa78-df1cf2be7ee1)
