### ISSUE TITLE
[Feature request]: Display of serviceProduct in timetable-row

### ISSUE THREAD

**Issue by WalkingOS** [lyne-design-system/lyne-components#2374]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### It affects the following packages

Components

### Functionality

Expected Outcome:
Display PE (without Linienbezeichnung GPX) in ttr.

Current Outcome:
PE is currently not displayed

**Comment by jeripeierSBB** [comment]
@WalkingOS will do this, right?
