### ISSUE TITLE
[Feature request]: change the color of the labels of the disabled radiobutton and checkbox

### ISSUE THREAD

**Issue by mcilurzo** [lyne-design-system/lyne-components#2384]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### It affects the following packages

Components

### Functionality

change request:
change the color of the labels of the disabled radiobutton and checkbox from charcoal to granite:

https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=277%3A113576&mode=design&t=nF8pNc4ixSmPoaot-1

https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=276%3A204784&mode=design&t=nF8pNc4ixSmPoaot-1

https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=12435%3A487112&mode=design&t=nF8pNc4ixSmPoaot-1

**Comment by TomMenga** [comment]
Hello @mcilurzo,
I have a quick doubt about the subtext of the `selection-panel`.
I see on Figma that the disabled `subtext` (the "Name" label) does not change from `granite => smoke` anymore.
Is it intended?

Figma:
![image](https://github.com/lyne-design-system/lyne-components/assets/12052575/6754dc03-e818-4ea9-ac52-1cd893ff537e)

**Comment by mcilurzo** [comment]
yes. the difference between smoke and granite is very small. It looks like a failure to me. also the contrast ratios were not optimal (3.07:1), so I adjusted it to granite (5.16:1).
