### ISSUE TITLE
[Question]: How do I get started with lyne-components?

### ISSUE THREAD

**Issue by sandrooco** [lyne-design-system/lyne-components#2388]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### It affects the following packages

Components

### Your Question

How do I get started with lyne-components?

### Give us a summary about your question

Hi, we're currently preparing for a project that should start around March/April. Since this is the target date for the Lyne base implementation as per [roadmap](https://confluence.sbb.ch/display/CLEW/ESTA-Web#ESTAWeb-Roadmap), we don't want to start the project with the old system to make sure we don't use an old system from day 1.

This is why I'm trying to set up a test project just to get a feel for how Lyne works at the moment. Yes, I'm aware that "_Lyne Components are 🧪experimental at the moment_". It seems that it should be stable enough for our internal project if it's already stable enough for sbb.ch. ;)

Currently there's no getting started section like with angular.app.sbb.ch - is it bad to assume we can just `npm i @sbb-esta/lyne-components` and import the components?

Thanks in advance.

**Comment by jeripeierSBB** [comment]
Hi @sandrooco 

We are going to include this kind of docs with version 1 (somewhen in spring). 
If you are planning to use it with Angular, with version 1 we will so far not provide a wrapper. This probably makes it difficult to use in some cases, but for sure you can use plain web components. 
We will provide more Angular support in later releases than version 1.

If you need help now, please contact me in Teams.

**Comment by sandrooco** [comment]
Hi @jeripeierSBB thanks for your feedback. This sounds great!
I'll contact you regarding a setup question via Teams shortly. Let's close this issue since it's tracked in #2392 already.
