### ISSUE TITLE
[Bug]: Jaws in Webcomponents 

### ISSUE THREAD

**Issue by SarahWigger** [lyne-design-system/lyne-components#2496]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Components

### Operating system

Windows 10

### Browser / Browser version

Tests with Screenreader JAWS 2024 & Chrome  Version 120.0.6099.225

### Input mode

None

### What happened?

Jaws in Webcomponents: When navigating with the tabulator, the screenreader doesn't identfiy links as links. When navigating in the browse mode, the screenreader behaves correctly. 

### Steps to reproduce the issue

Using Jaws in the tabulator mode and check some links, e.g. the footer links  or the links on the profile page on sbb.ch.

**Comment by jeripeierSBB** [comment]
Created a report at JAWS: https://github.com/FreedomScientific/standards-support/issues/816
