### ISSUE TITLE
[Bug]: sbb-menu positioning NOK

### ISSUE THREAD

**Issue by WalkingOS** [lyne-design-system/lyne-components#2567]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.40.9

### Operating system

Windows 10

### Browser / Browser version

Chrome

### Input mode

None

### What happened?

Description:
It appears that the sbb-menu isn't functioning properly when positioned at the bottom part of the viewport. Initially, the menu fails to display correctly. After some scrolling, the menu positioning abruptly corrects itself.

Actual Behavior:
The menu fails to display correctly initially, but corrects its position after scrolling.

Expected Behavior:
The sbb-menu should display always correctly without scrolling.

### Steps to reproduce the issue

1. Position the trigger for the sbb-menu at the bottom of the viewport.
2. press the trigger
3. sbb-menu open downwards
4. scroll up
5. sbb-menu corrects the position immediately

**Comment by jeripeierSBB** [comment]
Seems to be already fixed. Fix can be used with next release.
