### ISSUE TITLE
[Bug]: Failed to execute 'querySelector'

### ISSUE THREAD

**Issue by StefanBoehmeSBB** [lyne-design-system/lyne-components#2576]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.48.3

### Operating system

Windows 10

### Browser / Browser version

Chrome 123.0.6312.106 (Offizieller Build) (64-Bit)

### Input mode

None

### What happened?

Describe in detail the issue you are having.

We are using NewRelic to monitor the FE apps for www.sbb.ch and at the moment we are getting a lot of errors stating: "Failed to execute 'querySelectorAll' on 'Element': ':is(sbb-dialog, sbb-navigation, sbb-menu)[data-state='opened']' is not a valid selector."

Unfortunately i am not able to provide a click-path or something similiar only the error message!

What did you expect to happen? What happened instead? What would you like to see changed?
No error occurr.

Is the issue related to a specific component?
-

### Steps to reproduce the issue

See section above.

### Relevant log output

```shell
Error message:
Failed to execute 'querySelectorAll' on 'Element': ':is(sbb-dialog, sbb-navigation, sbb-menu)[data-state='opened']' is not a valid selector.
```

**Comment by jeripeierSBB** [comment]
As discussed in Teams, we close this issue without any change as browsers are very old. The `:is` selector is supported since Chrome version 88 (https://caniuse.com/css-matches-pseudo) which is way below our minimum (-2 versions).
