### ISSUE TITLE
lean: accordion / expansion-panel: size S

### ISSUE THREAD

**Issue by DavideMininni-Fincons** [lyne-design-system/lyne-components#2593]
https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=29314%3A1084359&mode=design&t=6s3eVNfR5eROI3dH-1

**Comment by DavideMininni-Fincons** [comment]
@kyubisation got two question about this: 
- the expansion-panel has no size prop; should i add it only there, or also in the accordion (forcing the size on the panel children)?
- it's ok to 'propagate' the size info to expansion-panel-header/content via `data-` prop?

**Comment by jeripeierSBB** [comment]
> @kyubisation got two question about this:
> 
> * the expansion-panel has no size prop; should i add it only there, or also in the accordion (forcing the size on the panel children)?
> * it's ok to 'propagate' the size info to expansion-panel-header/content via `data-` prop?

as expansion panel can be used standalone we should add a "normal" prop to either accordion (sync it down) and expansion panel itself.

**Comment by kyubisation** [comment]
Sorry, thought I hit comment on this.

What I originally wrote: Add a size property to both expansion panel and to accordion. Accordion should propagate size to its contained expansion-panels.
