### ISSUE TITLE
[Bug]: Error Displaying Uploaded Images in <sbb-image> Component

### ISSUE THREAD

**Issue by tobiasBlaser** [lyne-design-system/lyne-components#2595]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.49.0

### Operating system

Windows 10 / MacOS

### Browser / Browser version

Chrome 23.0.6312.123

### Input mode

None

### What happened?

We are developing a feature for file upload with preview using the <sbb-file-selector> and <sbb-image> components. 
We have encountered an issue where the <sbb-image> component fails to display images that are uploaded via the <sbb-file-selector>. 
However, the images can be displayed without issues using a native HTML <img> tag.

### Steps to reproduce the issue

We are developing a feature for file upload with preview using the <sbb-file-selector> and <sbb-image> components. 
We have encountered an issue where the <sbb-image> component fails to display images that are uploaded via the <sbb-file-selector>. 
However, the images can be displayed without issues using a native HTML <img> tag.
 
Steps to Reproduce:
1.) Use the <sbb-file-selector> component to upload an image file:
<sbb-file-selector
    ...
    (fileChanged)="uploadFile($event)"
>
    ...
</sbb-file-selector>
 
 
2.) The uploadFile function processes the uploaded file and stores the Blob URL in the media variable:
  public media = '';
 
  protected uploadFile(e: unknown): void {
    const files = (e as CustomEvent<File[]>).detail;
    if (files?.[0]) {
      this.media = URL.createObjectURL(files[0]);
      ...
    }
  }
 
 
3.) Attempt to display the image using the <sbb-image> component by binding the Blob URL to the imageSrc property:
<sbb-image [imageSrc]="media" [skipLqip]="true" />
 
 
Expected Behavior:
The <sbb-image> component should display the uploaded image similarly to how the native HTML <img> tag does.
 
Actual Behavior:
The <sbb-image> component triggers an error in the browser console:
  GET blob:http://localhost:4242/7857894b-3660-4ef0-b775-cf641775eeb1?auto=format%2Ccompress%2Ccs%3Dtinysrgb&w=976&h=549&q=45 
  net::ERR_FILE_NOT_FOUND
 
It appears that the component appends additional parameters such as format, compress, cs, w, h, and q to the URL, 
which are not part of the original Blob URL which looks like this:
  blob:http://localhost:4242/7857894b-3660-4ef0-b775-cf641775eeb1
 
Additional Information:
Using the property [skipLqip]="true" in the <sbb-image> component prevents an additional error from occurring but does not 
solve the image display issue. Both errors only occur with images uploaded internally via the file upload feature, 
while external URLs work without errors.

### Relevant log output

```shell
GET blob:http://localhost:4242/8730657a-16a7-4af1-99fc-1afe05adcf86?blur=100&w=100&h=56 net::ERR_FILE_NOT_FOUND

GET blob:http://localhost:4242/4bfe3820-0a17-4b64-b7a8-f882de7aca3a?auto=format%2Ccompress%2Ccs%3Dtinysrgb&w=2400&h=1350&q=20 net::ERR_FILE_NOT_FOUND
```

**Comment by jeripeierSBB** [comment]
Hi @tobiasBlaser 

The sbb-image is basically a helper for consuming images from the SBB image CDN. For your case, I recommned to use a normal <img> tag.
