### ISSUE TITLE
Deprecated Stencil output target: dist-custom-elements-bundle

### ISSUE THREAD

**Issue by feerglas** [lyne-design-system/lyne-components#946]
Stencil will deprecate the output target `dist-custom-elements-bundle`, which we heavily rely on our project and other projects like lyne-documentation, lyne-getting-started etc.

Stencil has open issues regarding this deprecation:
https://github.com/Esri/calcite-components/issues/3957
https://github.com/ionic-team/stencil/issues/3136

We should transition as soon as possible to the output target `dist-custom-elements`.

**Comment by DavideMininni-Fincons** [comment]
Useful link:
- the issue in Stencil
https://github.com/ionic-team/stencil/issues/3136
- a open PR in Stencil for an export-all-components 
https://github.com/ionic-team/stencil/pull/3368
- a closed PR in Ionic; note that a custom script is used to export everything (see folder scripts/custom-elements)
https://github.com/ionic-team/ionic-framework/pull/22863
- a closed PR in Ionic to update the starter component
https://github.com/ionic-team/stencil-component-starter/pull/107

Some bug related to the new setting:
https://github.com/ionic-team/stencil/issues?q=is%3Aissue+is%3Aopen+dist-custom-element

**Comment by jeripeierSBB** [comment]
Related to #1568

**Comment by jeripeierSBB** [comment]
Closed by #1568
