### ISSUE TITLE
Lyne Text Input Component with Angular Reactive Forms

### ISSUE THREAD

**Issue by reneboms** [lyne-design-system/lyne-components#990]
## Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/.github/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Environment

> Operating system Windows 10

> Browser / browser version - Microsoft Edge / 98.0.1108.43

## Which package(s) are you using?

- [x] `lyne-components`

## Detailed description

> Lyne Component Version:  9.73.1

I´m not able to use lyne-text-input components in combination with the angular ReactiveForms Module.
When I try to integrate the lyne input fields with the reactiveForms, in the console an ControleValueAccessor error is thrown.
Is there a way to implement the Angular ControleValueAccessor Interface into the Lyne Input Component, 
so that lyne form elements can be used together with the angular reactiveForms or Template Driven Forms?

### Code Example
Example Template driven form
```
<form>
        <div class="row">
          <lyne-text-input 
                           [(ngModel)]="newSupportCase.shortDescription"
                           name="shortDescription"
                           input-placeholder="Beschreibung ..."
                           label="Supportfall Beschreibung"></lyne-text-input>
        </div>
</form>
```

Example Reactive Forms
```
<form [formGroup]="formSupport">
        <div class="row">
          <lyne-text-input 
                           formControlName="shortDescription"
                           name="shortDescription"
                           input-placeholder="Beschreibung ..."
                           label="Supportfall Beschreibung"></lyne-text-input>
        </div>
</form>
```

## Additional information
Screenshot - Console Error
![image](https://user-images.githubusercontent.com/3024399/152970748-cefcacd6-3d35-4ae4-b055-a392a04341ab.png)

**Comment by kyubisation** [comment]
Should have been solved with the refactoring to `<sbb-form-field>`.
